name: terra-draw Release

permissions:
  contents: write
  id-token: write  # Required for OIDC

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.TERRA_DRAW_PAT }}

      - uses: actions/setup-node@v6
        with:
          node-version: "24.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install
        run: npm ci

      - name: Update Docs
        run: npm run docs

      - name: Run build
        working-directory: ./packages/terra-draw
        run: npm run build

      - name: Set git credentials
        run: |
          git config --global user.email "terradraw@githubactions.com"
          git config --global user.name "James Milner"

      - name: Release
        working-directory: ./packages/terra-draw
        run: npm run release

      - name: Push upstream
        run: git push origin main

      - name: Push tags upstream
        run: git push origin main --tags

      - name: Publish package
        run: npm publish
        working-directory: ./packages/terra-draw

      - name: Generate package release notes
        id: package_release_notes
        env:
          PACKAGE_NAME: terra-draw
          PACKAGE_DIR: packages/terra-draw
        run: node ./github-release.mjs

      - name: Create package GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ steps.package_release_notes.outputs.tag }}" --verify-tag --title "${{ steps.package_release_notes.outputs.title }}" --notes-file "${{ steps.package_release_notes.outputs.notes_file }}"
 